title: Jinsun Kim
logo: assets/Picture3.jpg
description: text below image 
Consumer Insights & Analytics Researcher with experience in mixed-method research and large-scale data analysis. Previously at GfK (now part of NielsenIQ) and CJ Foodville; currently at Talking Rain Beverage Company, makers of Sparkling Ice.
#show downloads: true 
theme: jekyll-theme-minimal
