title: Jinsun Kim 
logo: assets/Picture3.jpg
description: Consumer Insights & Analytic Researcher with experience in mixed-method research and large data analysis. Previously at GfK (now part of NielsenIQ) and CJ Foodville, currently at Talking Rain Beverage Company. 
[View my LinkedIn Profile](http://www.linkedin.com/in/kim-jinsun/)
